const router = require("express").Router()

const authRouter = require("./auth.route")
const hospitalRouter = require("./hospital.route")
const pathologyRouter = require("./pathology.route")
const userRouter = require("./user.route")
const doctorRouter = require("./doctor.route")
const pharmacyRouter = require("./pharmacy.route")
const businessRouter = require("./business.route")
const productRouter = require("./product.route")
const blobRouter = require("./blob.route")
const appointmentRouter = require("./appointment.route")
const orderRouter = require("./order.route")
const testRouter = require("./test.route")

router.use("/auth", authRouter)
router.use("/hospital", hospitalRouter)
router.use("/pathology", pathologyRouter)
router.use("/user", userRouter)
router.use("/doctor", doctorRouter)
router.use("/pharmacy", pharmacyRouter)
router.use("/business", businessRouter)
router.use("/product", productRouter)
router.use("/blob", blobRouter)
router.use("/appointment", appointmentRouter)
router.use("/order", orderRouter)
router.use("/test", testRouter)

module.exports = router
